### ISSUE TITLE
Checklist about Honeybee release

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-honeybee#39]
@ish-hcc (cc. @powerkimhub @innodreamer @sykim-etri @dev4unet)

안녕하세요. 

:date: Honeybee v0.2.x릴리스 일정을 11/11(월)로 계획하고 있습니다.

:raising_hand: 먼저, 관련하여 이슈가 있으신 경우 댓글로 남겨주시기 바랍니다.

:ballot_box_with_check: 아래 사항들에 대해 추진을 부탁드리며, 완료된 항목들은 Checked 처리하여 주십시오.
- [x] Honeybee 개발 및 테스트
- [x] Honeybee 관련 서브시스템과 통합 테스트 ([Sequence Diagram](https://github.com/cloud-barista/cloud-migrator/blob/main/docs/sequence-diagrams-for-user-scenarios.md) 참고 및 개선)
- [x] Honeybee 실행 지원
- [x] Honeybee 문서화
- [x] Honeybee 릴리스

각 항목별 자세한 사항은 아래 링크의 "저장소별 추진사항"을 참고하시면 될 것 같습니다.
Ref: https://github.com/cloud-barista/cloud-migrator/issues/11

아울러, 릴리스 이후 상위/타 서브시스템에서의 통합 및 테스트가 진행됩니다. 이 부분에 대해 미리 협조를 부탁드립니다.

(참고) 
이번 Cloud-Migrator v0.3.0 통합 및 릴리스는 두 가지 측면에서 진행됩니다.
* 컴퓨팅 인프라 마이그레이션: Cloud-Migration portal에서 3종 클라우드로, 3종 자원에 대해 마이그레이션을 수행할 수 있어야 함
* SW 마이그레이션: 기능 개발, 테스트 및 통합 추진 (portal 통합 대상 X)

**Comment by jollaman999** [comment]
@yunkon-kim 
박사님 안녕하세요? 최근에 테스트가 완료된 v0.2.10 cm-honeybee 릴리즈가 완료되어 알려 드립니다.
말씀 하신 부분들 모두 Check 완료 되었습니다.
소프트웨어 마이그레이션은 계속 개발 진행중이고 web 서버 대상으로 한 마이그레이션 테스트는 완료된 상태입니다.
앞으로 cm-cicada를 통해서 소프트웨어 마이그레이션이 되도록 추진되어야 할 것 같습니다.
감사합니다.

**Comment by yunkon-kim** [comment]
@jollaman999 @taking 고생 많으셨습니다!

사용자, Portal, Butterfly, Honeybee, Damselfly 간에 대략적인 인터렉션을 Sequence Diagram으로 공유 드렸었는데요. 일단은 이슈가 없으신 것으로 보고 다음 순서를 진행하겠습니다. 관련해서는 언제라도 의견 주시면 좋을 것 같습니다 :-)

그럼, Honeybee v0.2.10을 바탕으로 다음번 서브시스템 통합, 테스트 및 릴리스를 진행하도록 하겠습니다. 진행 과정에서 개선 사항이 도출 되면 대응을 부탁 드립니다.

@innodreamer @yunkon-kim @sykim-etri @dev4unet
담당하고 계신 서브시스템에서 Honeybee v0.2.10을 활용하셔서 (부분) 통합, 테스트 및 릴리스 진행해 주시기 바랍니다. 개선/조율이 필요한 사항이 있으시면 이슈를 열어주시면 될 것 같습니다. 

(참고) Honeybee에서 상시 구동 서버를 제공해주고 계시니 작업에 참고 바랍니다.
